---
title: "Graphs with R"
author: "Juanjo Sierra"
date: "27 de noviembre de 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Graphs with R: Exercises

First we need to load the ggplot2 library.

```{r}
library(ggplot2)
```


## 1) Plot distance against stretch.

```{r}
ex1 <- data.frame(stretch=c(46,54,48,50,44,42,52), distance=c(148,182,173,166,109,141,166))
ex1

ggplot(ex1, aes(distance, stretch)) + geom_point(col="blue", size=3)
```

## 2) The follwing data have ten observations taken during the years 1970-79, on October snow cover for Eurasia (snow cover is in millions of square kilometers).

```{r}
ex2 <- data.frame(year=c(1970:1979), snow.cover=c(6.5,12.0,14.9,10.0,10.7,7.9,21.9,12.5,14.5,9.2))
ex2
```

### Plot snow.cover versus year.

```{r}
ggplot(ex2, aes(snow.cover, year)) + geom_point(col="green", size=3)
```

### Plot a histogram of the snow.cover values.

```{r}
ggplot(ex2, aes(snow.cover)) + geom_histogram(fill="green", col="darkgreen", bins = 4)
```
